# Generated by Django 5.0 on 2023-12-31 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=55, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=7, default=1.0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('trakit_code', models.CharField(blank=True, max_length=256, null=True)),
                ('tech', models.CharField(blank=True, max_length=256, null=True)),
                ('trakit_description', models.CharField(blank=True, max_length=256, null=True)),
                ('trakit_formula', models.CharField(blank=True, max_length=256, null=True)),
                ('trakit_id', models.CharField(blank=True, max_length=256, null=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feetype')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_user', to='profiles.profile')),
                ('fees', models.ManyToManyField(to='payments.fee')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid_by', models.CharField(blank=True, max_length=256, null=True)),
                ('method', models.CharField(blank=True, max_length=256, null=True)),
                ('check_number', models.CharField(blank=True, max_length=256, null=True)),
                ('ib_number', models.CharField(blank=True, max_length=256, null=True)),
                ('receipt_number', models.PositiveSmallIntegerField(null=True)),
                ('collected_by', models.CharField(blank=True, max_length=256, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.cart')),
                ('fees', models.ManyToManyField(to='payments.fee')),
            ],
        ),
    ]
