# Generated by Django 5.0 on 2023-12-31 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_option_short', models.CharField(max_length=25, unique=True)),
                ('agency_option_full', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Partner Agency',
                'verbose_name_plural': 'Partner Agency Options',
                'ordering': ['agency_option_short'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_option_short', models.CharField(max_length=25, unique=True)),
                ('department_option_full', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Department Options',
                'ordering': ['department_option_short'],
            },
        ),
        migrations.CreateModel(
            name='DivisionOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_options', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Division Options',
                'ordering': ['division_options'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_short', models.CharField(max_length=7, unique=True)),
                ('agency_long', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'License Agency',
                'verbose_name_plural': 'License Agencies',
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_short', models.CharField(max_length=7, unique=True)),
                ('license_long', models.CharField(max_length=255, unique=True)),
                ('licensing_agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.licenseagency')),
            ],
            options={
                'verbose_name': 'License Type',
                'verbose_name_plural': 'License Types',
                'ordering': ['license_short'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100, verbose_name='First Name')),
                ('last', models.CharField(max_length=100, verbose_name='Last Name')),
                ('company_name', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=255, unique=True)),
                ('expiration_date', models.DateField()),
                ('verified_valid', models.BooleanField()),
                ('bl_number', models.CharField(blank=True, max_length=40, verbose_name='Yolo County Business License Number')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.licensetype')),
                ('license_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
            ],
            options={
                'ordering': ['license_holder', 'license_type'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_email', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.departmentoptions')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.divisionoptions')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profile', to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.CreateModel(
            name='YoloCountyPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alt_contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.agencyoptions')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
            ],
            options={
                'verbose_name_plural': 'Staff for Partner Agencies',
            },
        ),
    ]
