# Generated by Django 5.0 on 2024-01-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=2, unique=True)),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('build', models.BooleanField(default=False)),
                ('occupy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permit Status',
                'verbose_name_plural': 'Permit Statuses',
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('suffix', models.CharField(default='Ex-R', max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Permit Type',
                'verbose_name_plural': 'Permit Types',
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=55)),
                ('series_prefix', models.CharField(max_length=2)),
                ('year', models.DateTimeField(default='2024')),
                ('sequence', models.CharField(default='0000', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('policy', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PermitSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permittype')),
            ],
            options={
                'verbose_name': 'Permit Subtype',
                'verbose_name_plural': 'Permit Subtypes',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=55)),
                ('description', models.TextField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.siteaddress')),
                ('apn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.parcel')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apper', to='profiles.profile')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.division')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownries', to='profiles.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permitstatus')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permitsubtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permittype')),
            ],
            options={
                'verbose_name': 'Permit',
                'verbose_name_plural': 'Permits',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RelatedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField()),
                ('child_id', models.PositiveIntegerField()),
                ('child_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childeroo', to='contenttypes.contenttype')),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parenteroo', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Related Record',
                'verbose_name_plural': 'Related Records',
                'indexes': [models.Index(fields=['parent_type', 'parent_id', 'child_type', 'child_id'], name='permits_rel_parent__4be2da_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaggedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
                ('lock', models.BooleanField(default=False, verbose_name='Lock this record?')),
                ('lock_related', models.BooleanField(default=False, verbose_name='Lock related records?')),
                ('alert', models.BooleanField(default=True, verbose_name='Popup notification on this record?')),
                ('alert_related', models.BooleanField(default=False, verbose_name='Popup notification on related records?')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.tag')),
            ],
            options={
                'verbose_name': 'Tagged Record',
                'verbose_name_plural': 'Tagged Records',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='permits_tag_content_e818f8_idx')],
            },
        ),
    ]
