# Generated by Django 5.0 on 2024-01-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0003_sequence'),
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=2, unique=True)),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('build', models.BooleanField(default=False)),
                ('occupy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permit Status',
                'verbose_name_plural': 'Permit Statuses',
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('suffix', models.CharField(default='Ex-R', max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Permit Type',
                'verbose_name_plural': 'Permit Types',
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Workflow Type',
                'verbose_name_plural': 'Workflow Types',
                'ordering': ['workflow'],
            },
        ),
        migrations.CreateModel(
            name='PermitSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permittype')),
            ],
            options={
                'verbose_name': 'Permit Subtype',
                'verbose_name_plural': 'Permit Subtypes',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.siteaddress')),
                ('apn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.parcel')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apper', to='profiles.profile')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.division')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.sequence')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownries', to='profiles.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permitstatus')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permitsubtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permittype')),
                ('workflow_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.workflowtype')),
            ],
            options={
                'verbose_name': 'Permit',
                'verbose_name_plural': 'Permits',
                'ordering': ['number'],
            },
        ),
    ]
