# Generated by Django 5.0 on 2023-12-31 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=2, unique=True)),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('build', models.BooleanField(default=False)),
                ('occupy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Permit Status',
                'verbose_name_plural': 'Permit Statuses',
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('suffix', models.CharField(default='Ex-R', max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Permit Type',
                'verbose_name_plural': 'Permit Types',
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Workflow Type',
                'verbose_name_plural': 'Workflow Types',
                'ordering': ['workflow'],
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=30)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0.3, max_digits=3)),
                ('trip_factor', models.DecimalField(decimal_places=2, default=1.2, max_digits=7)),
                ('inspection_checklist', models.TextField(blank=True)),
                ('add_next', models.ManyToManyField(to='permits.inspectiontype')),
                ('default_inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.division')),
                ('inspection_fees', models.ManyToManyField(to='fees.feetype')),
                ('prerequisite', models.ManyToManyField(to='permits.inspectiontype')),
            ],
            options={
                'verbose_name': 'Inspection Type',
                'verbose_name_plural': 'Inspection Types',
            },
        ),
        migrations.CreateModel(
            name='PermitSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtype', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permittype')),
            ],
            options={
                'verbose_name': 'Permit Subtype',
                'verbose_name_plural': 'Permit Subtypes',
            },
        ),
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(max_length=30)),
                ('days_cycle1', models.PositiveSmallIntegerField(default=15)),
                ('days_cycle2', models.PositiveSmallIntegerField(default=5)),
                ('review_checklist', models.TextField(blank=True)),
                ('add_next', models.ManyToManyField(to='permits.reviewtype')),
                ('default_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revr', to=settings.AUTH_USER_MODEL)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.division')),
                ('prerequisite', models.ManyToManyField(to='permits.reviewtype')),
                ('review_fees', models.ManyToManyField(to='fees.feetype')),
            ],
            options={
                'verbose_name': 'Review Type',
                'verbose_name_plural': 'Review Types',
            },
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('year', models.SmallIntegerField(default='2023')),
                ('sequence', models.CharField(default='0000', max_length=4)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.siteaddress')),
                ('apn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.parcel')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apper', to='profiles.profile')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.division')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ownries', to='profiles.profile')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permitstatus')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permitsubtype')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permittype')),
                ('workflow_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.workflowtype')),
            ],
            options={
                'verbose_name': 'Permit',
                'verbose_name_plural': 'Permits',
                'ordering': ['year', 'sequence'],
            },
        ),
    ]
