# Generated by Django 5.0 on 2024-01-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_alter_feetype_options_remove_uigroup_fee_and_more'),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype',
            name='add_next',
            field=models.ManyToManyField(blank=True, to='permits.inspectiontype'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='inspection_fees',
            field=models.ManyToManyField(blank=True, to='fees.feetype'),
        ),
        migrations.AlterField(
            model_name='inspectiontype',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='permits.inspectiontype'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='year',
            field=models.SmallIntegerField(default='2024'),
        ),
    ]
