# Generated by Django 5.0 on 2024-01-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.division'),
        ),
        migrations.RemoveField(
            model_name='permitsubtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='subtype',
        ),
    ]
