# Generated by Django 5.0 on 2024-01-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_alter_permit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='number',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
