# Generated by Django 5.0 on 2024-01-11 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_alter_inspectiontype_division'),
        ('permits', '0002_alter_permit_division_remove_permitsubtype_type_and_more'),
        ('reviews', '0002_alter_reviewtype_review_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='PermitSubtype',
        ),
    ]
