# Generated by Django 5.0 on 2024-01-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(blank=True, max_length=4, null=True)),
                ('fund_label', models.CharField(blank=True, max_length=55, null=True)),
                ('share', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('unit', models.CharField(blank=True, max_length=4, null=True)),
                ('unit_label', models.CharField(blank=True, max_length=55, null=True)),
                ('unit_description', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_center', models.CharField(blank=True, max_length=6, null=True)),
                ('gl_account', models.CharField(blank=True, max_length=6, null=True)),
                ('cams', models.CharField(blank=True, max_length=9, null=True)),
                ('infor_activity', models.CharField(blank=True, max_length=7, null=True)),
                ('infor_account', models.CharField(blank=True, max_length=5, null=True)),
                ('ledger', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['fund', 'unit', 'cost_center'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=7, default=1.0, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('notes', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_group', models.CharField(max_length=255)),
                ('fee_name', models.CharField(max_length=255, unique=True)),
                ('policy', models.TextField(blank=True, max_length=1000)),
                ('authorization', models.CharField(blank=True, max_length=255)),
                ('adopted', models.DateField(blank=True, null=True)),
                ('revised', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('tier_base_qty', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('tier_base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('rate', models.FloatField(default=5000000)),
                ('units', models.CharField(default='each', max_length=255)),
                ('rate_check', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
                'ordering': ['fee_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('check_number', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_number', models.PositiveSmallIntegerField(null=True)),
                ('deposit', models.BooleanField(default=False)),
                ('refund', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=55, unique=True)),
                ('policy', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='ClaritiFee',
            fields=[
                ('fee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.fee')),
                ('clariti_fee_code', models.CharField(blank=True, max_length=255, null=True)),
                ('tech', models.CharField(blank=True, max_length=255, null=True)),
                ('clariti_description', models.CharField(blank=True, max_length=255, null=True)),
                ('clariti_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('clariti_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('fees.fee',),
        ),
        migrations.CreateModel(
            name='TrakitFee',
            fields=[
                ('fee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.fee')),
                ('trakit_fee_code', models.CharField(blank=True, max_length=255, null=True)),
                ('tech', models.CharField(blank=True, max_length=255, null=True)),
                ('trakit_description', models.CharField(blank=True, max_length=255, null=True)),
                ('trakit_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('trakit_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('fees.fee',),
        ),
    ]
