# Generated by Django 5.0 on 2023-12-31 00:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=6, unique=True)),
                ('unit_label', models.CharField(max_length=40, unique=True)),
                ('unit_description', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Budget Unit',
                'verbose_name_plural': 'Budget Units',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_label', models.CharField(max_length=30, unique=True)),
                ('fund_id', models.CharField(max_length=4, unique=True)),
                ('fund_description', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(max_length=255, unique=True)),
                ('policy', models.TextField(blank=True, max_length=1000, null=True)),
                ('authorization', models.CharField(blank=True, max_length=255, null=True)),
                ('adopted', models.DateField(blank=True, null=True)),
                ('revised', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('tier_base_qty', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('tier_base_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('rate', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('units', models.CharField(default='each', max_length=40)),
                ('rate_check', models.CharField(blank=True, max_length=40, null=True)),
                ('budget_unit_1_share', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('budget_unit_2_share', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MaxValueValidator(1.0)])),
                ('budget_unit_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fees.budgetunit')),
                ('budget_unit_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='split_fee', to='fees.budgetunit')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
            },
        ),
        migrations.AddField(
            model_name='budgetunit',
            name='unit_fund',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.fund'),
        ),
    ]
