# Generated by Django 5.0 on 2024-01-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund', models.CharField(max_length=4)),
                ('fund_label', models.CharField(max_length=55)),
                ('share', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('unit', models.CharField(max_length=4)),
                ('unit_label', models.CharField(max_length=55)),
                ('unit_description', models.CharField(max_length=255)),
                ('cost_center', models.CharField(max_length=6)),
                ('gl_account', models.CharField(max_length=6, unique=True)),
                ('cams', models.CharField(max_length=9)),
                ('infor_activity', models.CharField(max_length=7)),
                ('infor_account', models.CharField(max_length=5)),
                ('ledger', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('qty', models.DecimalField(decimal_places=7, default=1.0, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=25, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=1000000, max_digits=15)),
                ('fully_paid', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=55, unique=True)),
                ('policy', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.CreateModel(
            name='ClaritiFee',
            fields=[
                ('fee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.fee')),
            ],
            bases=('fees.fee',),
        ),
        migrations.CreateModel(
            name='TrakitFee',
            fields=[
                ('fee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.fee')),
                ('trakit_fee_code', models.CharField(blank=True, max_length=255, null=True)),
                ('tech', models.CharField(blank=True, max_length=255, null=True)),
                ('trakit_description', models.CharField(blank=True, max_length=255, null=True)),
                ('trakit_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('trakit_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('fees.fee',),
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_group', models.CharField(max_length=255, unique=True)),
                ('fee_type', models.CharField(max_length=255, unique=True)),
                ('policy', models.TextField(blank=True, max_length=1000, null=True)),
                ('authorization', models.CharField(blank=True, max_length=255, null=True)),
                ('adopted', models.DateField(blank=True, null=True)),
                ('revised', models.DateField(blank=True, null=True)),
                ('expires', models.DateField(blank=True, null=True)),
                ('tier_base_qty', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('tier_base_fee', models.FloatField(default=0)),
                ('rate', models.FloatField(default=5000000)),
                ('units', models.CharField(default='each', max_length=255)),
                ('rate_check', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('fee_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.account')),
            ],
            options={
                'verbose_name': 'Fee Type',
                'verbose_name_plural': 'Fee Types',
                'ordering': ['fee_type'],
            },
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feetype'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('check_number', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_number', models.PositiveSmallIntegerField(null=True)),
                ('deposit', models.BooleanField(default=False)),
                ('refund', models.BooleanField(default=False)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fees', models.ManyToManyField(to='fees.fee')),
                ('paid_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
