# Generated by Django 5.0 on 2024-01-15 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('profiles', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.record'),
        ),
        migrations.AddField(
            model_name='feetype',
            name='fee_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acct', to='fees.account'),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.feetype'),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='fees',
            field=models.ManyToManyField(to='fees.fee'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fees.paymentmethod'),
        ),
        migrations.AddField(
            model_name='claritifee',
            name='clariti_main_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clariti_fee', to='fees.fee'),
        ),
        migrations.AddField(
            model_name='trakitfee',
            name='trakit_main_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trakit_fee', to='fees.fee'),
        ),
    ]
