# Generated by Django 5.0 on 2024-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_trakitfee_main_fee_delete_claritifee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='fee_group',
            field=models.CharField(max_length=255),
        ),
    ]
