# Generated by Django 5.0 on 2023-12-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feetype_budget_unit_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
