# Generated by Django 5.0 on 2024-01-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claritifee',
            options={'ordering': ['clariti_main_fee'], 'verbose_name': 'Fee/Payment (Clariti)', 'verbose_name_plural': 'Fees/Payments (Clariti)'},
        ),
        migrations.AlterModelOptions(
            name='trakitfee',
            options={'ordering': ['trakit_main_fee'], 'verbose_name': 'Fee/Payment (Trakit)', 'verbose_name_plural': 'Fees/Payments (Trakit)'},
        ),
    ]
