# Generated by Django 5.0 on 2023-12-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feetype_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feetype',
            name='rate_check',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
