# Generated by Django 5.0 on 2023-12-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_remove_feetype_budget_unit_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uigroup',
            name='group',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
