# Generated by Django 5.0 on 2023-12-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_uigroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetype',
            name='budget_unit',
        ),
    ]
