# Generated by Django 5.0 on 2023-12-31 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_remove_feetype_budget_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'verbose_name': 'Budget Units and Funds', 'verbose_name_plural': 'Budget Units and Funds'},
        ),
        migrations.AlterModelOptions(
            name='uigroup',
            options={'verbose_name': 'Fee Group', 'verbose_name_plural': 'Fee Groups'},
        ),
        migrations.AlterModelOptions(
            name='unitportion',
            options={'verbose_name': 'Fee to Budget Unit Portions', 'verbose_name_plural': 'Fee to Budget Unit Portions'},
        ),
        migrations.RemoveField(
            model_name='uigroup',
            name='unit',
        ),
        migrations.AddField(
            model_name='feetype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.unitportion'),
        ),
    ]
