# Generated by Django 5.0 on 2023-12-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_alter_fund_options_alter_uigroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetype',
            name='unit',
        ),
        migrations.AddField(
            model_name='feetype',
            name='unit',
            field=models.ManyToManyField(through='fees.UnitPortion', to='fees.budgetunit'),
        ),
    ]
