# Generated by Django 5.0 on 2023-12-31 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_remove_feetype_unit_feetype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='uigroup',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.feetype'),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='fee_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.uigroup'),
        ),
    ]
