# Generated by Django 5.0 on 2024-01-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_uigroup_fee_alter_feetype_fee_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['fee_type'], 'verbose_name': 'Fee Type', 'verbose_name_plural': 'Fee Types'},
        ),
        migrations.RemoveField(
            model_name='uigroup',
            name='fee',
        ),
        migrations.AlterField(
            model_name='uigroup',
            name='group',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
