# Generated by Django 5.0 on 2023-12-31 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('policy', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField()),
                ('child_id', models.PositiveIntegerField()),
                ('child_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childeroo', to='contenttypes.contenttype')),
                ('parent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parenteroo', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Related Record',
                'verbose_name_plural': 'Related Records',
                'indexes': [models.Index(fields=['parent_type', 'parent_id', 'child_type', 'child_id'], name='general_rel_parent__220f01_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaggedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=255)),
                ('lock', models.BooleanField(default=False, verbose_name='Lock this record?')),
                ('lock_related', models.BooleanField(default=False, verbose_name='Lock related records?')),
                ('alert', models.BooleanField(default=True, verbose_name='Popup notification on this record?')),
                ('alert_related', models.BooleanField(default=False, verbose_name='Popup notification on related records?')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.tag')),
            ],
            options={
                'verbose_name': 'Tagged Record',
                'verbose_name_plural': 'Tagged Records',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='general_tag_content_5858a2_idx')],
            },
        ),
    ]
