# Generated by Django 5.0 on 2024-01-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='policy',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taggedrecord',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
