# Generated by Django 5.0 on 2024-01-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('permits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('causes_review_status', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Review Status Option',
                'verbose_name_plural': 'Review Status Options',
            },
        ),
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Review Status Option',
                'verbose_name_plural': 'Review Status Options',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coa', models.TextField(max_length=255, verbose_name='Conditions of Approval')),
                ('staff_time_allotted', models.DecimalField(decimal_places=1, max_digits=7)),
                ('staff_time_actual', models.DecimalField(decimal_places=1, max_digits=7)),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.permit')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.reviewstatus')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.PositiveSmallIntegerField(default=1)),
                ('reviewer', models.CharField(max_length=100, null=True)),
                ('completed_date', models.DateTimeField(null=True)),
                ('due', models.DateTimeField(null=True)),
                ('sent', models.DateTimeField(null=True)),
                ('notes', models.TextField(max_length=255)),
                ('staff_time_actual', models.DecimalField(decimal_places=1, max_digits=7)),
                ('days_until_due', models.DurationField(null=True)),
                ('age', models.DurationField(null=True)),
                ('days_allotted', models.DurationField(null=True)),
                ('result', models.ForeignKey(default='In Progress', on_delete=django.db.models.deletion.PROTECT, to='reviews.cycleresult')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.review')),
            ],
            options={
                'verbose_name': 'Review Cycle',
                'verbose_name_plural': 'Review Cycles',
            },
        ),
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(max_length=30)),
                ('days_cycle1', models.PositiveSmallIntegerField(default=15)),
                ('days_cycle2', models.PositiveSmallIntegerField(default=5)),
                ('review_checklist', models.TextField(blank=True, verbose_name='Review Checklist')),
                ('add_next', models.ManyToManyField(to='reviews.reviewtype')),
                ('default_reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prerequisite', models.ManyToManyField(to='reviews.reviewtype')),
                ('review_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='permits.division')),
                ('review_fees', models.ManyToManyField(related_name='+', to='fees.feetype')),
            ],
            options={
                'verbose_name': 'Review Type',
                'verbose_name_plural': 'Review Types',
            },
        ),
        migrations.AddField(
            model_name='review',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.reviewtype'),
        ),
    ]
