# Generated by Django 5.0 on 2024-01-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycleresult',
            options={'verbose_name': 'Cycle Result Option', 'verbose_name_plural': 'Cycle Result Options'},
        ),
        migrations.AlterField(
            model_name='reviewtype',
            name='add_next',
            field=models.ManyToManyField(blank=True, to='reviews.reviewtype'),
        ),
        migrations.AlterField(
            model_name='reviewtype',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='reviews.reviewtype'),
        ),
    ]
