# Generated by Django 5.0 on 2024-01-08 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_cycleresult_options_alter_reviewtype_add_next_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcycle',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle', to='reviews.review'),
        ),
    ]
