# Generated by Django 5.0 on 2024-01-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0001_initial'),
        ('inspections', '0001_initial'),
        ('locations', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Type',
                'verbose_name_plural': 'Contacts Types',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['form'],
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('prefix', models.CharField(max_length=2)),
                ('year', models.DateTimeField(default='2024')),
                ('number', models.CharField(default='0000', max_length=4)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['prefix', 'year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(blank=True, max_length=255, null=True)),
                ('lock', models.BooleanField(default=False, verbose_name='Lock this record?')),
                ('lock_related', models.BooleanField(default=False, verbose_name='Lock related records?')),
                ('alert', models.BooleanField(default=True, verbose_name='Popup notification on this record?')),
                ('alert_related', models.BooleanField(default=False, verbose_name='Popup notification on related records?')),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Restriction',
                'verbose_name_plural': 'Restrictions',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('build', models.BooleanField(default=False)),
                ('occupy', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('policy', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
                ('policy', models.CharField(max_length=255)),
                ('suffix', models.CharField(default='Ex-R', max_length=7, unique=True)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.contacttype')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['contact'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=55)),
                ('description', models.TextField(max_length=55)),
                ('details', models.TextField(max_length=255)),
                ('address', models.ManyToManyField(blank=True, to='locations.siteaddress')),
                ('apn', models.ManyToManyField(blank=True, to='locations.parcel')),
                ('app_questions', models.ManyToManyField(blank=True, to='records.question')),
                ('contacts', models.ManyToManyField(blank=True, through='records.Contact', to='profiles.profile')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.division')),
                ('fees', models.ManyToManyField(blank=True, through='fees.Fee', to='fees.feetype')),
                ('forms', models.ManyToManyField(blank=True, to='records.form')),
                ('inspections', models.ManyToManyField(blank=True, through='inspections.Inspection', to='inspections.inspectiontype')),
                ('related', models.ManyToManyField(blank=True, to='records.record')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'ordering': ['number'],
            },
        ),
    ]
