# Generated by Django 5.0 on 2024-01-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fees', '0002_initial'),
        ('inspections', '0002_initial'),
        ('records', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reviews',
            field=models.ManyToManyField(blank=True, through='reviews.Review', to='reviews.reviewtype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.record'),
        ),
        migrations.AddField(
            model_name='restriction',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.status'),
        ),
        migrations.AddField(
            model_name='restriction',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='records.tag'),
        ),
        migrations.AddField(
            model_name='type',
            name='default_app_questions',
            field=models.ManyToManyField(blank=True, to='records.question'),
        ),
        migrations.AddField(
            model_name='type',
            name='default_fees',
            field=models.ManyToManyField(blank=True, to='fees.feetype'),
        ),
        migrations.AddField(
            model_name='type',
            name='default_forms',
            field=models.ManyToManyField(blank=True, to='records.form'),
        ),
        migrations.AddField(
            model_name='type',
            name='default_inspection',
            field=models.ManyToManyField(blank=True, to='inspections.inspectiontype'),
        ),
        migrations.AddField(
            model_name='type',
            name='default_reviews',
            field=models.ManyToManyField(blank=True, to='reviews.reviewtype'),
        ),
        migrations.AddField(
            model_name='record',
            name='scope',
            field=models.ManyToManyField(blank=True, to='records.type'),
        ),
        migrations.AddIndex(
            model_name='restriction',
            index=models.Index(fields=['content_type', 'object_id'], name='records_res_content_ea4d2e_idx'),
        ),
    ]
