# Generated by Django 5.0 on 2024-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacttype',
            name='role',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
