# Generated by Django 5.0 on 2024-01-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_contacttype_role_form_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={'ordering': ['prefix', 'year', 'number'], 'verbose_name': 'Number', 'verbose_name_plural': 'Numbers'},
        ),
        migrations.AddField(
            model_name='type',
            name='division',
            field=models.CharField(default='', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type',
            name='prefix',
            field=models.CharField(default=' ', max_length=7),
        ),
        migrations.AlterField(
            model_name='type',
            name='suffix',
            field=models.CharField(default=' ', max_length=7),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
