# Generated by Django 5.0 on 2024-01-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_record_description_alter_record_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='scope',
        ),
    ]
