# Generated by Django 5.0 on 2024-01-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_remove_record_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='number',
            field=models.CharField(blank=True, max_length=55, unique=True),
        ),
    ]
