# Generated by Django 5.0 on 2024-01-18 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('records', '0008_alter_record_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(default='0000', max_length=12),
        ),
        migrations.AlterField(
            model_name='number',
            name='prefix',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='number',
            name='title',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='record',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.division'),
        ),
        migrations.AlterField(
            model_name='record',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.status'),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='records.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='policy',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
