# Generated by Django 5.0 on 2024-01-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15)),
                ('full_title', models.CharField(blank=True, max_length=255)),
                ('authority', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapter', to='codes.authority')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=55)),
                ('title', models.CharField(blank=True, max_length=55)),
                ('full_title', models.CharField(blank=True, max_length=255)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='chapter', to='codes.code')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=55)),
                ('title', models.CharField(blank=True, max_length=55)),
                ('full_title', models.CharField(blank=True, max_length=255)),
                ('chapter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='section', to='codes.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55)),
                ('text', models.CharField(blank=True, max_length=255)),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('section', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='requirement', to='codes.section')),
            ],
        ),
    ]
