# Generated by Django 5.0 on 2024-01-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'ordering': ['name'], 'verbose_name_plural': 'Authorities'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['title']},
        ),
    ]
