# Generated by Django 5.0 on 2024-01-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_time_allotted', models.DecimalField(decimal_places=1, max_digits=7)),
                ('staff_time_actual', models.DecimalField(decimal_places=1, max_digits=7)),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='InspectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=55)),
            ],
            options={
                'verbose_name': 'Inspection Group',
                'verbose_name_plural': 'Inspection Groups',
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=55, unique=True)),
                ('requirements', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Inspection Result Option',
                'verbose_name_plural': 'Inspection Result Options',
                'ordering': ['result'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.PositiveSmallIntegerField(default=0)),
                ('resulted', models.DateTimeField(null=True)),
                ('inspector', models.CharField(blank=True, max_length=100, null=True)),
                ('time_allotted', models.DecimalField(decimal_places=1, max_digits=7)),
                ('time_actual', models.DecimalField(decimal_places=1, max_digits=7)),
                ('time_delta', models.DecimalField(decimal_places=1, max_digits=7)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_date', models.DateField()),
                ('requested_notes', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Inspection Trip',
                'verbose_name_plural': 'Inspection Trips',
                'ordering': ['inspection', 'trip_number'],
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=255)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=0.3, max_digits=3)),
                ('trip_factor', models.DecimalField(decimal_places=2, default=1.2, max_digits=7)),
                ('inspection_checklist', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inspection Type',
                'verbose_name_plural': 'Inspection Types',
                'ordering': ['insp_group', 'inspection_type'],
            },
        ),
    ]
