# Generated by Django 5.0 on 2024-01-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits', '0002_alter_inspectiontype_add_next_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Inspection Result Option',
                'verbose_name_plural': 'Inspection Result Options',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_time_allotted', models.DecimalField(decimal_places=1, max_digits=7)),
                ('staff_time_actual', models.DecimalField(decimal_places=1, max_digits=7)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.inspectiontype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectionresult')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resulted', models.DateTimeField(null=True)),
                ('inspector', models.CharField(blank=True, max_length=100, null=True)),
                ('time_allotted', models.DecimalField(decimal_places=1, max_digits=7)),
                ('time_actual', models.DecimalField(decimal_places=1, max_digits=7)),
                ('time_delta', models.DecimalField(decimal_places=1, max_digits=7)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('requested_by', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_date', models.DateField()),
                ('requested_notes', models.CharField(blank=True, max_length=256, null=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspection')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectionresult')),
            ],
        ),
    ]
