# Generated by Django 5.0 on 2024-01-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='permits.division'),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='prerequisite',
            field=models.ManyToManyField(blank=True, to='inspections.inspectiontype'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectiontype'),
        ),
    ]
