# Generated by Django 5.0 on 2024-01-15 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='permit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='records.record'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectionresult'),
        ),
        migrations.AddField(
            model_name='inspectiontrip',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspection'),
        ),
        migrations.AddField(
            model_name='inspectiontrip',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectionresult'),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='default_inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='insp_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectiongroup'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.inspectiontype'),
        ),
    ]
