# Generated by Django 5.0 on 2024-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectiontype',
            name='inspection_type',
            field=models.CharField(max_length=255),
        ),
    ]
