# Generated by Django 5.0 on 2024-01-04 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'District Type',
                'verbose_name_plural': 'District Types',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city_state_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city_state_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.districttype')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(default='000', max_length=3)),
                ('page', models.CharField(default='000', max_length=3)),
                ('parcel', models.CharField(default='000', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=100, null=True)),
                ('land_use_zone', models.CharField(default='A-N', max_length=10)),
                ('wui_sra', models.BooleanField()),
                ('wui_lra', models.BooleanField()),
                ('wui_risk', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('wui_regulations', models.BooleanField()),
                ('flood_a', models.BooleanField()),
                ('flood_ae', models.BooleanField()),
                ('flood_ao', models.BooleanField()),
                ('flood_x', models.BooleanField()),
                ('floodway', models.BooleanField()),
                ('districts', models.ManyToManyField(to='locations.district')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.jurisdiction')),
                ('parents', models.ManyToManyField(to='locations.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='12345', max_length=10)),
                ('street', models.CharField(default='CR 98', max_length=50)),
                ('city', models.CharField(default='Woodland', max_length=50)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('zip', models.CharField(default='95695', max_length=5)),
                ('geolocation', models.CharField(blank=True, max_length=50, null=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.parcel')),
            ],
        ),
    ]
