# Generated by Django 5.0 on 2024-01-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityStZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=55)),
                ('zip', models.CharField(blank=True, max_length=25)),
            ],
            options={
                'verbose_name': 'City, State Zip',
                'verbose_name_plural': 'City, State Zip',
                'ordering': ['city', 'zip'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_type', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=55)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city_state_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['district'],
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Jurisdiction',
                'verbose_name_plural': 'Jurisdictions',
                'ordering': ['jurisdiction'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(default='000', max_length=3)),
                ('page', models.CharField(default='000', max_length=3)),
                ('parcel', models.CharField(default='000', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=100, null=True)),
                ('land_use_zone', models.CharField(default='A-N', max_length=10)),
                ('wui_sra', models.BooleanField()),
                ('wui_lra', models.BooleanField()),
                ('wui_risk', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('wui_regulations', models.BooleanField()),
                ('flood_a', models.BooleanField()),
                ('flood_ae', models.BooleanField()),
                ('flood_ao', models.BooleanField()),
                ('flood_x', models.BooleanField()),
                ('floodway', models.BooleanField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('districts', models.ManyToManyField(blank=True, to='locations.district')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.jurisdiction')),
                ('parcels', models.ManyToManyField(blank=True, to='locations.parcel')),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'ordering': ['book', 'page', 'parcel'],
            },
        ),
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='12345', max_length=10)),
                ('street', models.CharField(default='County Road 98', max_length=50)),
                ('geolocation', models.CharField(blank=True, max_length=50, null=True)),
                ('city_st_zip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.citystzip')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.parcel')),
            ],
            options={
                'verbose_name': 'Site Address',
                'verbose_name_plural': 'Site Addresses',
                'ordering': ['number', 'street', 'city_st_zip'],
            },
        ),
    ]
