# Generated by Django 5.0 on 2024-01-15 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteaddress',
            name='city_st_zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.citystzip', verbose_name='City, State, Zip'),
        ),
    ]
