# Generated by Django 5.0 on 2024-01-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='related',
            new_name='parcels',
        ),
        migrations.AddField(
            model_name='parcel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcel',
            name='districts',
            field=models.ManyToManyField(blank=True, to='locations.district'),
        ),
        migrations.AlterField(
            model_name='siteaddress',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.parcel'),
        ),
    ]
