# Generated by Django 5.0 on 2024-01-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_rename_related_parcel_parcels_parcel_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityStZip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=55)),
                ('zip', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='siteaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='siteaddress',
            name='zip',
        ),
        migrations.AlterField(
            model_name='siteaddress',
            name='street',
            field=models.CharField(default='County Road 98', max_length=50),
        ),
        migrations.AddField(
            model_name='siteaddress',
            name='city_st_zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.citystzip'),
        ),
    ]
