# Generated by Django 5.0 on 2024-01-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_siteaddress_city_st_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='object_id',
        ),
    ]
