# Generated by Django 5.0 on 2024-01-18 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits_bp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demolition',
            old_name='building_area',
            new_name='demolition_area',
        ),
        migrations.RemoveField(
            model_name='demolition',
            name='inspections',
        ),
        migrations.RemoveField(
            model_name='demolition',
            name='reviews',
        ),
    ]
