# Generated by Django 5.0 on 2024-01-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permits_bp', '0001_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.reviewtype'),
        ),
        migrations.AddField(
            model_name='reroof',
            name='bp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='permits_bp.building'),
        ),
    ]
