# Generated by Django 5.0 on 2024-01-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits_bp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantrole',
            options={'verbose_name': 'Applicant Role', 'verbose_name_plural': 'Applicant Roles'},
        ),
        migrations.AlterModelOptions(
            name='floodzones',
            options={'verbose_name': 'Flood Zone', 'verbose_name_plural': 'Flood Zones'},
        ),
        migrations.AlterModelOptions(
            name='ownerrole',
            options={'verbose_name': 'Owner Role', 'verbose_name_plural': 'Owner Roles'},
        ),
        migrations.RenameField(
            model_name='applicantrole',
            old_name='applicant_role_options',
            new_name='applicant_role',
        ),
        migrations.RenameField(
            model_name='ownerrole',
            old_name='owner_role_options',
            new_name='owner_role',
        ),
    ]
