# Generated by Django 5.0 on 2024-01-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits_bp', '0002_alter_applicantrole_options_alter_floodzones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerrole',
            name='owner_role',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
