# Generated by Django 5.0 on 2024-01-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits_bp', '0003_alter_ownerrole_owner_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicantrole',
            options={'verbose_name': 'Applicant Role Option', 'verbose_name_plural': 'Applicant Role Options'},
        ),
        migrations.AlterField(
            model_name='applicantrole',
            name='applicant_role',
            field=models.TextField(max_length=55, unique=True, verbose_name='Applicant Role'),
        ),
        migrations.AlterField(
            model_name='floodzones',
            name='zone_code',
            field=models.CharField(max_length=7, verbose_name='Flood Zone Code'),
        ),
        migrations.AlterField(
            model_name='floodzones',
            name='zone_description',
            field=models.CharField(max_length=255, verbose_name='Flood Zone Description'),
        ),
    ]
