# Generated by Django 5.0 on 2024-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_initial'),
        ('permits_bp', '0004_alter_applicantrole_options_and_more'),
        ('reviews', '0003_alter_reviewcycle_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='inspections',
            field=models.ManyToManyField(blank=True, to='inspections.inspectiontype'),
        ),
        migrations.AddField(
            model_name='pool',
            name='notes',
            field=models.TextField(default='', max_length=255, verbose_name='Notes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.reviewtype'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='area',
            field=models.PositiveIntegerField(default=1000, verbose_name='Area (square feet)'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='depth',
            field=models.PositiveIntegerField(default=6, verbose_name='Feet'),
        ),
    ]
