# Generated by Django 5.0 on 2024-01-08 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits_bp', '0005_pool_inspections_pool_notes_pool_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='depth',
            field=models.PositiveIntegerField(default=6, verbose_name='Depth (feet)'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='notes',
            field=models.TextField(blank=True, max_length=255, verbose_name='Notes'),
        ),
    ]
