# Generated by Django 5.0.1 on 2024-01-08 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits_bp', '0006_alter_pool_depth_alter_pool_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bp',
            options={'verbose_name': 'Building Permits', 'verbose_name_plural': 'Building Permits'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'New Building/Structure', 'verbose_name_plural': 'New Buildings/Structures'},
        ),
    ]
